### ISSUE TITLE
Use acon in the pre-trained model

### ISSUE THREAD

**Issue by chenshen03** [nmaac/acon#7]
Hi, thanks for your amazing work!
How to use ACON in the pre-trained model? Can I directly replace all activation functions in the ImageNet pre-trained network with ACON, and then finetune it in the downstream task?

**Comment by nmaac** [comment]
@chenshen03 I did not try this, but I think you should finetune it on the ImageNet first.

**Comment by chenshen03** [comment]
> @chenshen03 I did not try this, but I think you should finetune it on the ImageNet first.

Thank you for your reply.
Therefore, the best way may be train the acon-equipped network from scratch on imagenet, and then finetune it in the downstream task?

**Comment by nmaac** [comment]
yes
